### ISSUE TITLE
Docker usage and yt-dlp complains about Bad Request, is yt-dlp too old?

### ISSUE THREAD

**Issue by ReindeerFan** [jim60105/YoutubeLiveChatToDiscord#12]
I was trying to use this script with the direct copy paste line:
`docker run --rm ghcr.io/jim60105/youtubelivechattodiscord [Video_Id] [Discord_Webhook_Url]`

It tries several times these checks and ultimately fails:
```
fail: YoutubeLiveChatToDiscord.Services.LiveChatDownloadService[0]
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.

WARNING: [youtube] Unable to download API page: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>); 
please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. 
Confirm you are on the latest version using  yt-dlp -U
```

I used to get same kind of errors when yt-dlp wasn't updated on the host machine when using the same yt-dlp for other purposes.
What could be the solution or should updated yt-dlp somehow be included in the docker?

**Comment by jim60105** [comment]
I trigger the CI build workflow just now, the `latest` tag is now build with yt_dlp-2024.4.9.
Please try again with `docker run --rm --pull always ghcr.io/jim60105/youtubelivechattodiscord`
https://github.com/jim60105/YoutubeLiveChatToDiscord/actions/runs/8741584094

**Comment by jim60105** [comment]
@ReindeerFan Please confirm whether the issue has been resolved or provide additional information.
I cannot reproduce this issue on my platform, it is working fine.

**Comment by ReindeerFan** [comment]
@jim60105 Thanks for your brief reply and update. It seems that chat is now rolling nicely to Discord.
